FROM debian:bullseye

RUN apt-get update && apt-get install -y mariadb-server \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists* /tmp* /var/tmp/*

EXPOSE 3306

COPY ../mariadb/docker-entrypoint.sh /usr/local/bin
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

COPY ../mariadb/my.cnf /etc/mysql/my.cnf

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]